Android書籍管理アプリAPIレビュー (続き）
iikeda-cq/BookManager-Android pull request #3
Opened 2020-08-24 09:47 UTC by iikeda-cq

## 概要
Android書籍管理アプリのAPIを作成しました。

コンフリクト修正の際に誤って、プルリクをクローズしてしまったためこれは2つ目のプルリクになります。

お手数ですが、第一レビューアの鎌田さんまでのプルリクと一緒にご確認をお願いします。
[Android書籍管理アプリAPIレビュー #2](https://github.com/iikeda-cq/BookManager-Android/pull/2)

2020-08-25 06:57 UTC, skamada-cq approved these changes
遅くなりすいません、差分的には大丈夫そうです
お疲れ様でした 🙏 

口頭でお伝えした通り実際の案件ではmaster、developに直接コミットやmasterにforce pushすることはないと思ってください！
(本当は今回もmasterを戻してforce push以外の手段が思いつけば避けたいくらいでした、、、)

2020-08-25 07:03 UTC, iikeda-cq commented
@skamada-cq 
ご確認いただきありがとうございます:bow:

pushについて、これから改めて意識していきたいとおもいます。

2020-08-25 10:36 UTC, daikawa-cq reviewed
いくつかコメントしましたので、確認お願いします 🙏

2020-08-25 10:36 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/SettingFragment.java
> +        String token = getToken(Objects.requireNonNull(getContext()));
`requireContext()`が便利です。

2020-08-25 10:36 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/model/Book.java
> +        return this.name;
thisは不要かと。

2020-08-25 10:36 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/util/APIRequest.java
> +    Call<BookListResponse> setUpBookList(
getBookListの方が良いかな。
GETだし。

2020-08-25 10:36 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/util/APIRequest.java
> +            @Header("access_token") String token,
複数回使用するなら定数使った方が良さそう。

2020-08-25 10:36 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/util/SharedPreferencesUtil.java
> +        context.getSharedPreferences("my_settings", Context.MODE_PRIVATE)
複数回使用するなら定数使った方が良さそう。

2020-08-26 02:38 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +            alert(R.string.empty_image, this);
最初に
`if (imageView == null) {`で実装したのですがうまくいかなかったため、上記のような実装にしていました。

しかし、`if (imageView.getDrawable() == null) {`でnullチェックが実装できたため修正しました。

2020-08-26 02:38 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +                    Log.e(TAG, "Something wrong On Response: " + response.toString());
`Log.e(TAG, "Something wrong On Response: " + response.toString(), new Throwable());`に修正しました！

2020-08-26 02:39 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/SettingFragment.java
> +        String token = getToken(Objects.requireNonNull(getContext()));
`requireContext()`に修正しました！

2020-08-26 02:40 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +    private boolean checkInputDate(String title, String price, String purchaseDate) {
imageを引数に含むよう修正しました！

2020-08-26 02:40 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +                if (checkInputDate(title, price, purchaseDate)) {
`isValidInputData`にメソッド名を直しました。

2020-08-26 02:43 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +            Glide.with(holder.view.getContext()).load(book.getImage()).into(holder.imageView);
リストをスクロールした際に、画像設定されていないデータに他データの画像が残ってしまうことがあったため、
画像がない時はclearするように実装しました。

未設定画像を追加し、それを表示するように修正しました:bow:

2020-08-26 02:46 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/LoginActivity.java
> +                            Toast.makeText(LoginActivity.this, R.string.login_failure, Toast.LENGTH_LONG).show();
breakを追加しました。
switch文を抜けた後に、ログを出力しているのですがこれのことではないですか？

2020-08-26 02:57 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/BookListFragment.java
> +                        return;
最終ページ到達以降、APIを呼ばないように処理したく、このように実行しました。

```
if (!recyclerView.canScrollVertically(1) && !isLoading) {
                    currentPage = currentPage + 1;
                    fetchBook(currentPage, LIMIT);
                }
```
trueのままだと、それ以降fetchBookが呼ばれないため、問題ないと認識しています。

2020-08-26 03:32 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +            Glide.with(holder.view.getContext()).clear(holder.imageView);
contextだとコンパイルエラーが発生してしまいました。

2020-08-26 03:32 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/util/APIRequest.java
> +    Call<BookListResponse> setUpBookList(
getBookListに修正しました！

2020-08-26 03:38 UTC, iikeda-cq commented
@daikawa-cq 
お忙しいところレビューしてくださりありがとうございます:bow:

指摘箇所の修正が完了したため、再度ご確認お願いします！

2020-08-26 04:23 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +            Glide.with(holder.view.getContext()).clear(holder.imageView);
自分はコンパイルできてますね。。。
もうちょっと確認してみてください。

2020-08-26 04:38 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +            Glide.with(holder.view.getContext()).clear(holder.imageView);
すみません、`context`で確認できました！
`Glide.with(context).load(book.getImage()).into(holder.imageView);`

2020-08-27 04:04 UTC, daikawa-cq reviewed
いくつかコメントしましたので、確認お願いします 🙏

2020-08-27 06:18 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +        public final View view;
viewを削除しました！

2020-08-27 06:19 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +            imageString = convertImage(imageView);
言われてみるとおっしゃる通りですね。
`convertImage`を呼び出す箇所を修正しました。

2020-08-27 06:20 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +        APIRequest apiService = APIClient.retrofit.create(APIRequest.class);
修正しました。

2020-08-27 06:36 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +                    Log.e(TAG, "Something wrong On Response: " + response.toString(), new Throwable());
ログ出力について修正しました！

2020-08-27 07:12 UTC, iikeda-cq commented
@daikawa-cq 
ご確認いただきありがとうございます:bow:

https://github.com/iikeda-cq/BookManager-Android/pull/3#discussion_r477865052 すみませんが、ここの実装についてご指摘通りなっているか自信がないのでお手隙の際にご確認をお願いします。

2020-08-27 08:23 UTC, daikawa-cq approved these changes
いくつかコメントしましたので、確認お願いします 🙏 
問題なければ、飯野さんレビューに進んでください。

2020-08-27 08:23 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/util/ApiRequest.java
> +package com.example.bookmanager_android.util;
utilフォルダには入れないかな。
今あるフォルダならmodelフォルダかなと思います。ApiClientも同様です。

2020-08-27 08:23 UTC, daikawa-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +                String purchaseDate = purchaseDateEditText.getText().toString();
`EditText purchaseDateEditText`はフィールドでいいかもしれないですね。。
複数箇所で使用してますし。
```
private EditText purchaseDateEditText;

@Override
protected void onCreate(Bundle savedInstanceState) {
    ...
    purchaseDateEditText = findViewById(R.id.purchase_date_edit_text);
    setDatePicker(purchaseDateEditText, this);
}

@Override
public boolean onOptionsItemSelected(@NonNull MenuItem item) {
    ...
    purchaseDate = purchaseDateEditText.getText().toString();
```

2020-08-27 08:46 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/util/ApiRequest.java
> +package com.example.bookmanager_android.util;
ApiRequest/ApiClientをmodelフォルダに移動させました。

2020-08-27 10:50 UTC, yiino-cq requested changes
:eyes:ed

2020-08-27 10:50 UTC, yiino-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/BookListFragment.java
> +                        return;
研修ではこれでOKですが実務的にはNGです。
isLoadingが"ロード中"以外に"最終ページまで取得済み"という複数の一見しただけではわからない意味を含んでいるのがよくないです。

2020-08-27 10:50 UTC, yiino-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/BookListFragment.java
> +                        return;
あと通信失敗時にも以降読み込み不可になってるのであれば良くないので修正してみてください

2020-08-28 01:33 UTC, iikeda-cq commented on app/build.gradle
> +    testImplementation 'junit:junit:4.12'
`testImplementation 'junit:junit:4.12'`を一番下に移動させました。

2020-08-28 01:37 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +                    Log.e(TAG, "Something wrong On Response: " + response.toString());
例外がない際に例外をインスタンス化しないこと承知いたしました。

ログのErrorとWarningの区別に関してもありがとうございます、勉強になります！

2020-08-28 02:22 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/BookListRecyclerViewAdapter.java
> +        if (book.getPrice() != null) {
金額未設定の際に`ー円+税`と表示するよう修正しました。

2020-08-28 02:23 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/activity/AddBookActivity.java
> +    private boolean isValidInputDate(String title, String price, String purchaseDate, ImageView imageView) {
すみません、タイプミスです。。
Dataに直しました！

2020-08-28 02:28 UTC, iikeda-cq commented on app/src/main/java/com/example/bookmanager_android/fragment/BookListFragment.java
> +                        return;
isLoadingが複数の意味を含んでしまっているため、よくないことわかりました。
また、通信失敗時に`isLoading = false`にするように修正しました。

2020-08-28 02:33 UTC, iikeda-cq commented
@yiino-cq 
お忙しいところレビューしてくださりありがとうございます！

ご指摘いただいた箇所の修正が完了したため、ご確認お願いします:bow:

2020-08-28 02:40 UTC, yiino-cq approved these changes
`金額未設定時の処理を修正` このコミットに実際にはその他いろんな修正が入っています。
コミットメッセージと修正内容は一致させるようにしましょう
修正は問題ないとと思うので一旦ここまででOKと思います。:yosasou:
お疲れさまでした 🙆‍♀️

2020-08-28 02:40 UTC, yiino-cq commented on app/build.gradle
> +    testImplementation 'junit:junit:4.12'
androidTestImplementationにも注目

2020-08-28 02:46 UTC, iikeda-cq commented
@yiino-cq 
早急のご確認ありがとうございます！

すみません、コミットメッセージに関して気をつけます。
レビューしていただきありがとうございました:bow:

2020-08-28 05:00 UTC, merged